In [39]:
import numpy as np
import copy

In [2]:
threshold=0.00001
base=0.8

In [37]:
A=np.array([[1,1,0],[1,0,1],[0,1,0]])

In [30]:
s=[]
for i in range(len(A)):
    s.append(np.sum(A[:,i]))
s

[2, 2, 1]

In [48]:
M = copy.deepcopy(A).astype(float)
print(A)
print(M)

[[1 1 0]
 [1 0 1]
 [0 1 0]]
[[1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]


In [49]:
for i in range(0,len(A)):
    M[:,i]=M[:,i]/s[i]
print(A)
print(M)

[[1 1 0]
 [1 0 1]
 [0 1 0]]
[[0.5 0.5 0. ]
 [0.5 0.  1. ]
 [0.  0.5 0. ]]


In [55]:
rank_vector = np.ones(len(M)) / len(M)
rank_vector

array([0.33333333, 0.33333333, 0.33333333])

In [57]:
c=(1-base)*rank_vector
c

array([0.06666667, 0.06666667, 0.06666667])

In [58]:
r_prev=rank_vector
r_prev

array([0.33333333, 0.33333333, 0.33333333])

In [62]:
for i in range(1,1001):
    rank_vector=base*np.matmul(M,r_prev)+c
    diff=np.sum(abs(r_prev-rank_vector))
    if(diff<threshold):
        break
    r_prev=rank_vector
rank_vector

array([0.3763434 , 0.39785125, 0.22580535])